name: Build and Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.19.0
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      - name: Generate build
        run: npm run build
        working-directory: ./frontend

      - name: Commit and Push
        run: |
          # Configure git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Navigate into the build directory
          cd frontend/build

          # Create a new branch and push the contents of the build directory
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          git init
          git add .
          git commit -m "Add build artifacts"
          git push origin `git subtree split --prefix=$(pwd)`:refs/heads/build/$BRANCH_NAME --force
          
      # Create Pull Request to release/v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Add build artifacts"
          title: "New Build Artifacts for Release"
          body: "Auto-generated pull request to merge build artifacts into release/v1"
          branch: "build/$BRANCH_NAME"
          base: "release/v1"

