name: Build and Create Pull Request

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      - name: Generate build
        run: npm run build
        working-directory: ./frontend

      - name: Prepare Artifacts
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
    
          # Copy build artifacts from the frontend build directory to the root directory
          cp -a frontend/build/. .
    
          # Stage the changes
          git add .

      - name: Commit and Push Artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          BRANCH_NAME="build-artifacts-$(date +'%Y%m%d-%H%M%S')"
          
          if git diff --quiet --staged; then
            echo "No changes to commit."
            exit 0
          fi

          # Commit the changes
          git commit -m "Add build artifacts"
          
          # Create a new branch and push the commit
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          PR_TITLE="Automated Build Artifacts Update"
          PR_BODY="Latest build artifacts for client files"
          BRANCH_NAME="build-artifacts-$(date +'%Y%m%d-%H%M%S')"
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base master --head "$BRANCH_NAME"
