name: Build and Create Pull Request

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      
      - name: Generate build
        run: npm run build
        working-directory: ./frontend

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
    
          # Define the branch name dynamically based on the current ref
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
      
          # Create a new branch from the current branch
          git checkout -b build/$BRANCH_NAME
     
          # Copy build artifacts from the frontend build directory to the root directory
          # Ensure the destination directory is correct according to your project structure
          cp -a frontend/build/. .
     
          # Add all changes to git
          git add .
      
          # Commit the changes
          git commit -m "Add build artifacts"
    
          # Push the branch to the remote repository
          git push -u https://x-access-token:${GH_TOKEN}@github.com/HarryZ10/Journex-Platform.git build/$BRANCH_NAME

      # Create Pull Request to release/v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${GH_TOKEN}
          commit-message: "Add build artifacts"
          title: "New Build Artifacts for Release"
          body: "Auto-generated pull request to merge build artifacts into release/v1"
          branch: "build/$BRANCH_NAME"
          base: "release/v1"

